
USE Gestion;
-- CREATION DE LA TABLE CLIENTS 
CREATE TABLE IF NOT EXISTS Clients
(
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    _NAME_ VARCHAR(100),
    EMAIL VARCHAR(255),
    MONAME VARCHAR(100),
    QUANTITE VARCHAR(100),
    VALEUR VARCHAR(100),
    TOTAL VARCHAR(250)
)
;
-- CREATION BLOCKCHAINE 

CREATE TABLE IF NOT EXISTS Users
(
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    id_user INTEGER,
    MONAME VARCHAR(100),
    QUANTITE INTEGER,
    PRIX_UNITE INTEGER,
    GAIN INTEGER,
    TOTAL INTEGER
)
;

CREATE USER IF NOT EXISTS 'yoan'@'192.168.163.1' IDENTIFIED WITH mysql_native_password BY 'AzErTy123*';
-- CREATION DU USER, METTRE SON NOM ET SON @IP DE MACHINE WINDOWS
GRANT ALL ON Gestion.* TO 'yoan'@'192.168.163.1';
-- DONNE TOUS LES DROITS, METTRE SON NOM ET SON @IP DE MACHINE WINDOWS
FLUSH PRIVILEGES;
-- APPLIQUE LES DROITS QU'ON VIENT DE DONNER

SHOW DATABASES;
-- PERMET DE VOIR LES BASES DE DONNEES PRESENTES
SHOW TABLES;
-- PERMET DE VOIR LES TABLES DE LA BASE DE DONNEE UTILISER
select user,host from mysql.user;
-- PERMET DE VOIR LES USAGERS PRESENTS DANS LE SERVICE MYSQL